let
    Source = Excel.Workbook(File.Contents("E:\STUDY\1.POWER BI\Data Set\2.Bike_Data.xlsx"), null, true),
    TrainingSample2_Sheet = Source{[Item="TrainingSample2",Kind="Sheet"]}[Data],
    #"Promoted Headers" = Table.PromoteHeaders(TrainingSample2_Sheet, [PromoteAllScalars=true]),
    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Region", type text}, {"Country", type text}, {"Customer", type text}, {"Business Segment", type text}, {"Category", type text}, {"Model", type text}, {"Color", type text}, {"SalesDate", type date}, {"ListPrice", type number}, {"UnitPrice", type number}, {"OrderQty", Int64.Type}}),
    #"Removed Columns" = Table.RemoveColumns(#"Changed Type",{"Region", "Country", "Business Segment", "Color"}),
    #"Inserted Day of Year" = Table.AddColumn(#"Removed Columns", "Day of Year", each Date.DayOfYear([SalesDate]), Int64.Type),
    #"Inserted Lowercased Text" = Table.AddColumn(#"Inserted Day of Year", "lowercase", each Text.Lower([Customer]), type text),
    #"Inserted Capitalize Each Word" = Table.AddColumn(#"Inserted Lowercased Text", "Capitalize Each Word", each Text.Proper([lowercase]), type text),
    #"Inserted Text Before Delimiter" = Table.AddColumn(#"Inserted Capitalize Each Word", "Text Before Delimiter", each Text.BeforeDelimiter([Capitalize Each Word], " "), type text),
    #"Inserted Text After Delimiter" = Table.AddColumn(#"Inserted Text Before Delimiter", "Text After Delimiter", each Text.AfterDelimiter([Capitalize Each Word], " "), type text),
    #"Inserted Week of Year" = Table.AddColumn(#"Inserted Text After Delimiter", "Week of Year", each Date.WeekOfYear([SalesDate]), Int64.Type),
    #"Inserted Week of Month" = Table.AddColumn(#"Inserted Week of Year", "Week of Month", each Date.WeekOfMonth([SalesDate]), Int64.Type)
in
    #"Inserted Week of Month"
